//GET ALL USERS
GET https://react-airbnb-clone-backend.onrender.com/users
###

//GET A SINGLE USER
GET https://react-airbnb-clone-backend.onrender.com/users/1
###

// GET ALL BOOKINGS

https://react-airbnb-clone-backend.onrender.com/bookings
###

// GET ALL BOOKINGS FOR A USER

GET https://react-airbnb-clone-backend.onrender.com/bookings?userId=1

###
https://react-airbnb-clone-backend.onrender.com/listings
###

# POST http://localhost:5000/posts
# Content-Type: application/json

#    {
#         "title": "airbnb clone",
#         "author": "Lesego"
#     }
